// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4zSs24S7YtZlhwdHMKezFZsi1yWa52A',
    appId: '1:262985379449:web:3deea7968a62d0193deea8',
    messagingSenderId: '262985379449',
    projectId: 'card-trading-24029',
    authDomain: 'card-trading-24029.firebaseapp.com',
    storageBucket: 'card-trading-24029.firebasestorage.app',
    measurementId: 'G-TGXM92X151',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdKiS1mL-ZXSGGRWpN3hSof8Q5ohdS1U',
    appId: '1:262985379449:android:6a1fc618893bcdc73deea8',
    messagingSenderId: '262985379449',
    projectId: 'card-trading-24029',
    storageBucket: 'card-trading-24029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TZ0LEgTL9Tx1imNwSf8V4eWWilQRHA0',
    appId: '1:262985379449:ios:a740988a0207450b3deea8',
    messagingSenderId: '262985379449',
    projectId: 'card-trading-24029',
    storageBucket: 'card-trading-24029.firebasestorage.app',
    iosBundleId: 'com.example.cardTrading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TZ0LEgTL9Tx1imNwSf8V4eWWilQRHA0',
    appId: '1:262985379449:ios:a740988a0207450b3deea8',
    messagingSenderId: '262985379449',
    projectId: 'card-trading-24029',
    storageBucket: 'card-trading-24029.firebasestorage.app',
    iosBundleId: 'com.example.cardTrading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4zSs24S7YtZlhwdHMKezFZsi1yWa52A',
    appId: '1:262985379449:web:4b754a7dc77183963deea8',
    messagingSenderId: '262985379449',
    projectId: 'card-trading-24029',
    authDomain: 'card-trading-24029.firebaseapp.com',
    storageBucket: 'card-trading-24029.firebasestorage.app',
    measurementId: 'G-SFFNEZL4PD',
  );
}
